<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ELMS.Helpers\ELMS.Helpers.csproj" />
    <ProjectReference Include="..\ELMS.Models\ELMS.Models.csproj" />
    <ProjectReference Include="..\ELMS.Services\ELMS.Services.csproj" />
  </ItemGroup>

</Project>
